### PR TITLE
Add option for vector origin

### PR DESCRIPTION
**Pull request by syockit**
This was a feature request.
Origin of each vector can be set to center of its cell, in addition to the default option tail.

### CODE REVIEW

**Comment by grahamrow** [comment]
Hi Ahmad, thanks for submitting this request. I'll take a look this afternoon.

**Comment by grahamrow** [comment]
Feature looks great, just wondering whether you think the controls should move into the "Sprites" tab?

**Comment by syockit** [comment]
Yeah, I was wondering too. Maybe it should go to sprites after all, as all other settings regarding vector is located there.

**Comment by syockit** [comment]
Branch is rebased to `grahamrow:master`.
Option moved Sprites tab, as a second vertical layout. I plan to put another option there for scaling the sprites against the maximum magnitude.

Unfortunately, Preferences window got a bit wider :p

P/S: I had to do a force push on this branch as rebasing caused strange commits to appear. Any tips on how to add features seamlessly?

**Comment by grahamrow** [comment]
Great, we'll have some more room to add features in the right column there. I'm almost done adding user defined color schemes, so I needed some more space in the first tab. Thanks again for the code.

**Comment by grahamrow** [comment]
Not sure about the rebasing issues — things went smoothly when I merged your code. Sometimes I need to force a push to the remote branch after rebasing, which I presume has something to do with whether the commits can be FFed.

**Pull request merged**
